# Application info
info.app:
  name: @project.name@
  description: @project.description@

# Loggers
logging.level:
  root: WARN
  @project.groupId@: INFO

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

# Database
spring:
  jpa:
    open-in-view: false
  show-sql: true
  properties.hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
