# Application info
info.app:
  name: Weather Store
  description: Storage service for weather conditions

# Actuator
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always

# Database
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
