name: Clean Up
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  Clean-Up-GHCR:
    name: Clean Up GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Delete 1 day old release candidates
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.REPOSITORY }}
          cut-off: One day ago UTC
          filter-tags: rc.*
          account-type: personal
          token: ${{ secrets.PACKAGES_PAT }}